### ISSUE TITLE
Database connectivity tool

### ISSUE THREAD

**Issue by leisenstein** [mulesoft-labs/net-tools-api#13]
Would be nice to have a database connectivity tool.
- host, port, dbname, user pass

Is there a way to test this currently using the tools?

**Comment by titans-of-code** [comment]
This is not intended to support any protocols other than the basic linux network utilities.  Database functionality will not be added.  You can usually test basic connectivity by using the socket option and hitting the database listening port.  That is how we use this to check DB connectivity.
