### ISSUE TITLE
Wrong Mime type is returned

### ISSUE THREAD

**Issue by robday-sf** [mulesoft-labs/net-tools-api#21]
The Java script is returned as 'text/html' instead of 'text/javascript'. This causes issues when using HTTPS on some browsers. This is not the case for css files. This is because in the project you can then find the flow:
'ui-css'.

If you look at the path, this is set to "/css/*". If you then click on the Listener and then the 'MIME Type' option on the basic settings, you can see is set to:
text/css

This flow then calls the 'ui' reference.

The same should be be true for the .js files. There should be a 'ui-js' flow which sets the path to "/js/*" and the 'MIME Type' should be set to 'text/javascript'.

**Comment by titans-of-code** [comment]
This has been addressed since 3.4.0 version.
