### ISSUE TITLE
Wrong link

### ISSUE THREAD

**Issue by chriscatuk** [mulesoft-labs/net-tools-api#8]
The link to v2.1.0 is wrong in Mulesoft documentation: https://help.mulesoft.com/s/article/How-To-Use-Network-Tools-Application (on the very bottom or the page).

It shows correctly net-tools-v2.1.0.jar, but when we click the link is actually https://s3.amazonaws.com/support-ops/net-tools/net-tools-mule4-v1.0.1.jar

**Comment by yyamano** [comment]
@chriscatuk I think the link is already fixed.
